# Generated by Django 5.0.4 on 2024-04-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='is_disabled',
        ),
    ]
